server:
  port: 8014
  context-path: /driver-api/
  tomcat:
    max-connections: 300
    max-threads: 1000

spring:
  datasource:
    name: carservicedev
    url: jdbc:mysql://172.20.94.27:3306/carservicetest?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: sysroot
    password: pass1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  freemarker:
    check-template-location: false
  redis:
    host: 172.20.94.26
    port: 6379
    password: xxkj@2017
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  jmx:
    enabled: false
  rabbitmq:
    username: rabbitadmin
    password: rytaxi1234
    virtual-host: DevAPPServer
    addresses: 172.20.94.26

  boot:
    admin:
      url: http://172.20.94.20/spring-admin-web/
      username: ${security.user.name}
      password: ${security.user.password}
      client:
        metadata:
           user.name: ${security.user.name}
           user.password: ${security.user.password}
        name: driver-api
        management-base-url: http://172.20.94.20/driver-api
        service-base-url: http://172.20.94.20

security:
    user:
      name: admin
      password: 123456
      role: admin
    basic:
      path: /actuator
management:
  security:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:public/mybatis-configuration.xml

swagger:
  enable: true
