server:
  port: 8002
  context-path: /driver-api/
  tomcat:
    max-connections: 300
    max-threads: 1000

spring:
  datasource:
    name: carservicedev
    url: jdbc:mysql://10.131.92.33:3306/carserviceres?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: hycroot
    password: ryds@2017
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  freemarker:
    check-template-location: false
  redis:
    host: 10.131.92.22
    port: 6379
    password: ryds@2017
    timeout: 3000
    pool:
      max-idle: 50
      min-idle: 1
      max-active: 500
      max-wait: 300
  jmx:
    enabled: false
  rabbitmq:
    username: appuser
    password: appuser@yc2017
    virtual-host: APPServer
    addresses: 10.131.92.24:5672

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:public/mybatis-configuration.xml

security:
    basic:
      enabled: false

swagger:
  enable: true
