server:
  port: 8013
  context-path: /driver-api/
  tomcat:
    max-connections: 300
    max-threads: 1000

spring:
  datasource:
    name: carservicedev
    url: jdbc:mysql://10.131.95.133:3306/carservicetest?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: hycroot
    password: ryds@2017
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  freemarker:
    check-template-location: false
  redis:
    host: 10.131.95.122
    port: 6379
    password: ryds@2017
    timeout: 3000
    pool:
      max-idle: 500
      min-idle: 300
      max-active: 500
      max-wait: 300
  jmx:
    enabled: false
  rabbitmq:
    username: appuser
    password: appuser@yc2017
    virtual-host: APPServer
    addresses: 10.131.95.137:5672
  boot: 
    admin:
      url: https://rytaxitest.xunxintech.com:8081/spring-admin-web/
      username: ${security.user.name}       #配置在客户端
      password: ${security.user.password}   #保护监控端api
      client:
        metadata:
          user.name: ${security.user.name}    #配置在服务端
          user.password: ${security.user.password} #保护客户端api
        name: driver-api
        management-base-url: http://rytaxitest.xunxintech.com:8081/driver-api
        service-base-url: http://rytaxitest.xunxintech.com:8081
        
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:public/mybatis-configuration.xml

security:
  user:
    name: admin  #安全账号，保护api
    password: 123456
    role: admin
  basic:
    path: /actuator     #配置actuator路径

swagger:
  enable: true

