server:
  port: 8008
  context-path: /driver-api/
  tomcat:
    max-connections: 300
    max-threads: 1000

spring:
  datasource:
    name: carservicedev
    url: jdbc:mysql://10.10.10.101:3306/sham_carservice_sham_v4.0.0?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: sham
    password: yc@123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  freemarker:
    check-template-location: false
  redis:
    host: 10.10.10.101
    port: 6379
    timeout: 3000
    pool:
      max-idle: 8
      min-idle: 1
      max-active: 8
      max-wait: 300
  jmx:
    enabled: false
  rabbitmq:
    username: whzj01
    password: 123456
    virtual-host: ShamAPPServer
    addresses: 10.10.10.101:5672

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:public/mybatis-configuration.xml

security:
    basic:
      enabled: false

swagger:
  enable: true

