server:
  port: 2000
  context-path: /driver-api/
  tomcat:
    max-connections: 300
    max-threads: 1000

spring:
  datasource:
    name: carservicedev
    url: jdbc:mysql://szycwh.f3322.net:3306/carservicedev_v4.0.0?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: developer
    password: yc@123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  freemarker:
    check-template-location: false
  redis:
    host: szycwh.f3322.net
    port: 6380
    password: yc@123456
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  jmx:
    enabled: false
  rabbitmq:
    username: whzj01
    password: 123456
    virtual-host: LocalAPPServer
    addresses: 10.10.10.101:5672

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:public/mybatis-configuration.xml

security:
    basic:
      enabled: false

swagger:
  enable: true